name: Write Current Time to File

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  write_time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current time
        run: |
          current_time=$(date "+%Y-%m-%d %H:%M:%S")
          echo "Current time: $current_time"
          echo "$current_time" > current_time.txt

      - name: Get current user
        run: |
          user_name="${{ github.actor }}"
          user_email="${{ github.actor }}@users.noreply.github.com"
          echo "Current user: $user_name"
          echo "User email: $user_email"

      - name: Commit and push time to file
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git add current_time.txt
          git commit -m "Update current time by ${user_name}"
          git push
