
name: time

on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Configure Git
      run: |
        current_time=$(date "+%Y-%m-%d %H:%M:%S")
        echo "Current time: $current_time"
        echo "$current_time" > current_time.txt
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "commit message"
        git push origin main --force
